### ISSUE TITLE
wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by MOHAMADKHOSHNAVA** [acrcloud/acrcloud_sdk_python#21]
```Traceback (most recent call last):
  File "bot.py", line 25, in <module>
    from acrcloud.recognizer import ACRCloudRecognizer
  File "/usr/local/lib/python3.7/dist-packages/acrcloud/recognizer.py", line 21, in <module>
    import acrcloud_extr_tool
ImportError: /usr/local/lib/python3.7/dist-packages/acrcloud/acrcloud_extr_tool.so: wrong ELF class: ELFCLASS64
```

**Comment by taosd** [comment]
I too am experiencing this issue - I am using a Raspberry Pi 2 with Python 3.7.3. I've installed acrcoud_sdk_python by running:

```
python3 -m pip install git+https://github.com/acrcloud/acrcloud_sdk_python
```

Any suggestions?

**Comment by taosd** [comment]
Alright - got this working this evening. As I am on a raspberry pi - I had to run the specific installer for it for the x86 architecture.  I did this by running

```
sudo acrcloud_sdk_python/raspberrypi/x86/python3/setup.py install
```

from there everything worked as expected
